// import Header from './Components/Header'
import React from 'react'
import Notification from './components/Notification'
import './globals.css'

import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'RadheyKrishna R.-Mohit Yadav',
  description: 'Generated by Mohit Yadav',
}

export default function RootLayout({ children }) {
  return (
     <html lang="en">
      <body className=''>
<Notification/>
<Navbar/>

      {children}
      <Footer/></body>
    </html>
  )
}
